keycode = {
    'a': 65,
    'b': 66,
    'c': 67,
    'd': 68,
    'e': 69,
    'f': 70,
    'g': 71,
    'h': 72,
    'i': 73,
    'j': 74,
    'k': 75,
    'l': 76,
    'm': 77,
    'n': 78,
    'o': 79,
    'p': 80,
    'q': 81,
    'r': 82,
    's': 83,
    't': 84,
    'u': 85,
    'v': 86,
    'w': 87,
    'x': 88,
    'y': 89,
    'z': 90,
    '0': 48,
    '1': 49,
    '2': 50,
    '3': 51,
    '4': 52,
    '5': 53,
    '6': 54,
    '7': 55,
    '8': 56,
    '9': 57
}


def convert_keycode(input):
    result = ''
    for item in input:
        result += str(keycode[item]) + ','
    result = result[:-1]
    result += ' 0'
    print(result)


def main():
    positive_input = ['fjdkls', 'fjdkls', 'fjdksl', 'jfkdls', 'ghfjdk', 'hfjdks', 'fhdjks', 'fhdjskl', 'fhdjks',
                      'fhdjksl', 'fgdhjsk', 'ghfjdksl', 'fgdhsjka', 'fgdhjsk', 'vbcnxmz', 'vbcnxmz', 'vbcnxzm',
                      'cbnxmz', 'vbcnxmz', 'vbcnxmz', 'vbcxnzm', 'vcbxnzm', 'vbcnxmz', 'tryeuiw', 'tryeuwi',
                      'tryeuwiqo', 'yreuiwo', 'tyrueiow', 'ryeuwio', 'ryueiwo', 'yreuiwoq', 'tyreuiwo', 'ryeuiwo',
                      'yrueiwoq', 'tyruei', 'vcbxnm', 'fgdhsjka', 'tryeuwi', 'fjdks', 'fgdhjlska', 'gfhdjks',
                      'gdhsjakl', 'vcbnxmz', 'fgdhjskal', 'vcbxnmz', 'tryeuwioq', 'rteywuiqo', 'yrueiwop', 'treywuiq',
                      'ytruieowpq', 'vcbxnzm', 'dgshjak', 'rteywuio', 'dghsjakl', 'tryeuwioqp', 'gdhsjka', 'fgdhjs',
                      'vcbxn', 'fdgshj', 'fgdhsjk', 'gfdhjsk', 'gshajkl', 'fdgshajk', 'gfhdjskl', 'rtyeuwio',
                      'gfdhsjkl', 'vcbxnm', 'tyrueiow', 'tyrueiwo', 'fghj', 'tewyui', 'tyreuiow', 'ryeuwio', 'etwyquio',
                      'yreuiwop', 'fgdhsjkl', 'bcxz', 'fgdhsjakl', 'ryeuio', 'yreuiwo', 'yrueiow', 'yrueiwo',
                      'tryeuwio', 'fgdhsjk', 'vcbnxmz', 'fgdhsjk', 'tryeuiwo', 'fgdhsjk', 'cvbxnm', 'fgdhsjk',
                      'rteywuio', 'tyurioep', 'dfsghaj', 'cvxbnzm', 'rtyeuiw', 'vcxbnzm', 'gdhsjak', 'ryueiow',
                      'tryeuiw', 'tyreuiw', 'ytuiroep', 'etwyuqio', 'yuitropew', 'rwtyuqio', 'yutiroep', 'treyuwiqo',
                      'yrueiwopw', 'ytuirope', 'rueiowp', 'uwiopq', 'ryueiwo', 'ureiowp', 'ywuqio', 'gfhdjksl',
                      'fsghaj', 'ghfjdksl', 'dgshjak', 'hfdjksl', 'hfdjksl', 'jdskla', 'fhdjksla', 'gfhdjk', 'gfdhjska',
                      'fhdjksl', 'vbcnmx', 'cbxnzm', 'cbnxmx', 'vcbxnm', 'bznm', 'bcnxm', 'cbxnzm', 'bcnxm', 'bcnxzm',
                      'cbxnm', 'vbcnxmz', 'vcbxnz', 'vbcnxmz', 'bxnzm', 'vcxbnzm', 'cbxnzm', 'vbcnxm', 'yreuiw',
                      'trueiow', 'utiroep', 'hfdjksl', 'yeuwiqop', 'uewioq', 'dhsjk', 'hfdjksls', 'ureiowp', 'dhsjk',
                      'ryueiwo', 'dhsjak', 'yrueiow', 'fdhjsk', 'cbxnm', 'cvbxnm', 'ryeui', 'gdhsj', 'tyruieo', 'cbnxm',
                      'utrieo', 'fgdhsj', 'rteyuwi', 'utrieo', 'cxhjz', 'fdhjsk', 'tyurieow', 'gdhsjak', 'ryeuwio',
                      'hfjdk', 'uyitorp', 'gfhdjsk', 'tryeuiw', 'vcbnxmz', 'fgdhjsk', 'tryeuiw', 'gfdhsjk', 'vcbxnmz',
                      'yutiroe', 'uyitorp', 'erwtqyui', 'fdgshja', 'cvbxnzm', 'ghfjdkl', 'yturieo', 'gfdhsj',
                      'retwyuqi', 'uyiotpr', 'hgjfkd', 'bvcnxm', 'dfsghaj', 'vbcnxmz', 'fgdhjsk', 'gfhdjks', 'fjdksl',
                      'gdhsj', 'gshajk', 'hgjfkdl', 'gfhdjks', 'tryeuiw', 'cvxbnz', 'dfgshaj', 'rteywui', 'yutiorp',
                      'gfhdjsk', 'cvbxnm', 'gfhdjsk', 'dfsgahj', 'cvxbnzm', 'tyrueio'
                      ]
    negtive_input = ['uhv', 'rghn', 'xfyu', 'erthn', 'cvghui', 'rth', 'ergh', 'dfyui', 'sdfj', 'njio', 'sxc', 'vghui',
                     'ertghn', 'drtyui', 'rtyj', 'wertyj', 'cgui', 'xfyuio', 'rthjm', 'xdfyuio', 'rthjm', 'cghuio',
                     'wedfb', 'xfghu', 'ijm', 'oih', 'efefgh', 'serfghj', 'cfyuk', 'ertyhbn', 'xdthj', 'tyuhgcx',
                     'wsdfghj', 'iuytrdc', 'fgui', 'sfdgfh', 'hfsd', 'sbhjiu', 'weuh', 'bchui', 'xcfgyu', 'rth',
                     'werty', 'oiug', 'drtyh', 'xcvbhu', 'poiuyg', 'qwscv', 'cyui', 'oiuytf', 'ertyhn', 'qscvb', 'cfyu',
                     'oiuyt', 'kjhv', 'srtyu', 'zxcgyu', 'iuytrd', 'zsrtyj', 'cgh', 'iuyg', 'erth', 'sertyui',
                     'cfgyuio', 'oiuytd', 'wdfghj', 'xcghui', 'dtyui', 'rdftgh', 'gvhu', 'txrfuygk', 'ijiuh', 'vghj',
                     'xcfg', 'iuyf', 'edfghjk', 'xfyui', 'nhre', 'asdfgui', 'cgui', 'dfghn', 'dfghj', 'yuio', 'oihg',
                     'rghn', 'xfyui', 'uygfc', 'efgh', 'hgfrfghn', 'cfghu', 'uigyuf', 'ezrtxgfk', 'hgdv', 'ashck',
                     'qvebick', 'qxgk', 'sdabhvioz', 'weiurdacsb', 'zuvcdgks', 'sdjivhs', 'wqfbucow', 'bdhuca', 'bsaf',
                     'efbiwuo', 'sdauhicg', 'wudviy', 'vbieuo', 'bfhjwa', 'sbjkadv', 'qbufw', 'abiu', 'bxiueo', 'abvio',
                     'absvidghs', 'bjscgiu', 'hfiea', 'sdiaco', 'biufa', 'baivsoa', 'bcuaui', 'bwisvbid', 'vdsbaico',
                     'bahcoei', 'cftyh', 'rtyh', 'xftyujb', 'cfyhb', 'erfvhj', 'jhhu', 'iuhsc', 'hacl', 'dsbkvj',
                     'asuhdke', 'sjbzckh', 'wauef', 'vbhes', 'zhuiexh', 'aiuehc', 'sbhdiak', 'bahscek', 'bhusave',
                     'irghd', 'saiode', 'weriuy', 'sbhdocb', 'aiufh', 'weirg', 'xvbis', 'woefuh', 'abiuewf', 'xibcvb',
                     'rigoj', 'qwydbh', 'zise', 'ergh', 'xvisa', 'siuhfh', 'zbisd', 'rgoijz', 'vniesrn', 'eahfng',
                     'naoen', 'oefanjk', 'aowrjk', 'isuevnjk''asdkh', 'asduasd', 'bcish', 'sdiagv', 'aiyfcv',
                     'awuiegfbc', 'zxhc', 'saeioj', 'bsnidu', 'qdsvg', 'sbthov', 'csuv', 'ersughbv', 'bcuys', 'rgohavb',
                     'qwdvuc', 'dsvui', 'zcvuye']
    swipe_right = ['tyui', 'tyuio', 'tyuiop', 'rtyuio', 'wertyui', 'qwertyu', 'wertyu', 'ertyui', 'rtyuio', 'sdfghj',
                   'xcvbnm', 'sdfghjk', 'ertyui', 'ertyuio', 'sdfghj', 'ertyui', 'dfghj', 'dfghjk', 'ertyuio', 'dfghj',
                   'xcvbnm', 'ertyui', 'dfghj', 'xcvbnm', 'ertyui', 'wertyu', 'sdfgh', 'zxcvbn', 'ertyuio', 'dfghj',
                   'dcvbnm', 'rtyui', 'dfghj', 'zxcvbn', 'rtyuio', 'sdfghjk', 'dfghjk', 'asdfghj', 'ertyuio', 'wertyj',
                   'rtyui', 'dfgh', 'xcvbn', 'yuio', 'dfghj', 'tyuio', 'werty', 'cvbn', 'fghjk', 'tyuio', 'werty',
                   'sdfgh', 'cvbn', 'yuio', 'dfghj', 'asdfgh', 'xcvbn', 'tyui', 'ertyu', 'dfghjk', 'xcvbn', 'sdfgh',
                   'rtyuio', 'wertyu', 'dfghj', 'xcvbn', 'dfghjk', 'tyuio', 'dfghj', 'cvbn', 'fghjk', 'tyuio', 'rtyui',
                   'yuiop', 'tyuiop', 'ghjk', 'cvhj', 'dfghjk', 'ertyu', 'wertyu', 'fghjk', 'rtyu', 'cvb', 'asdfg',
                   'rtyui', 'xcvbnm', 'cvbnm', 'vbnmwert', 'qwer', 'uiop', 'tyuio', 'dfgh', 'ghjkl', 'sdfgh', 'xcvbn',
                   'rtyu', 'sdfgh', 'xcvbn', 'zxcvbn', 'asdfgh', 'qwerty', 'rtyui', 'ertyui', 'tyrion', 'yup', 'sdfghj',
                   'ghjkl', 'dfghjk', 'asdfghj', 'asdfgh', 'zxcvbn', 'cvbnm', 'zxcvbn', 'xcvbn', 'cvbn', 'ertyu',
                   'wert', 'dfghj', 'asdfgh', 'tyuio', 'rtyu', 'tyui', 'yuio', 'ertyui', 'asdf', 'fight', 'ghjkl',
                   'asdfg', 'dfghj', 'sdfgh', 'ghjk', 'rtyu', 'wertyu', 'qwer', 'ertyu', 'rtyu', 'wert', 'tyui', 'yuio',
                   'yuiop', 'uiop', 'tyuio', 'ertyu', 'asdf', 'sdfgh', 'dfgh', 'fghj', 'ghjk', 'ghjk', 'hjkl', 'dfghj',
                   'zxcvb', 'zxcvbn', 'xcvbn', 'cvbnm', 'cvbn', 'vbnm', 'zxcvbn', 'dfghj', 'werty', 'rtyui', 'yuiop',
                   'fghjk', 'ghjkl', 'sdfgh', 'asdfgh', 'sdfghj', 'fghjkl', 'ghjk', 'xcvbn', 'vbnm', 'zxcv', 'cvbnm',
                   'qwe', 'qwer', 'qwert', 'qwerty', 'qwertyu', 'qwertyui', 'qwertyuio', 'wert', 'werty', 'wertyu',
                   'wertyui', 'wertyuio', 'wertyuiop', 'ertyui', 'ertyuio', 'ertyuiop', 'rty', 'rtyu', 'rtyui',
                   'rtyuio', 'rtyuiop', 'tyu', 'tyui', 'tyuio', 'tyuiop', 'yui', 'yuio', 'yuiop', 'uiop', 'asdf',
                   'sdfg', 'dfghj', 'fghjk', 'ghjkl', 'asdfgh', 'asdfghjk', 'sdfghjkl', 'dfghjkl', 'fghjkl', 'ghjkl',
                   'zxcv', 'xcvbn', 'cvbnm', 'cvbnm', 'zxcvbnm'
                   ]
    swipe_left = ['uytre', 'hgfd', 'nbvcx', 'jhgfds', 'ytrew', 'uytre', 'oiuytr', 'poiuyt', 'kjhg', 'nbvc', 'hgfd',
                  'iuytr', 'hgfds', 'bvcx', 'rewq', 'gfds', 'bvcxz', 'hgfdsa', 'ytrewq', 'hgfdsa', 'bvcxz', 'nbvcxz',
                  'mnbvcxz', 'kjhgfds', 'kjhgfd', 'oiuyt', 'oiuytr', 'jhg', 'bvc', 'ytre', 'hgfds', 'iuytre', 'bvcx',
                  'gfds', 'jhgfds', 'ytrew', 'iuytr', 'nbvcx', 'jhgfds', 'poiuytr', 'jhgfd', 'nbvcx', 'hgfds', 'ytrew',
                  'jhgfd', 'nbvcx', 'hgfdsa', 'uytrew', 'bvcxz', 'hgfds', 'vcxz', 'kjhgfd', 'poiuyt', 'gfdsa', 'ytrew',
                  'gfds', 'bvcxz', 'rewq', 'gfdsa', 'nbvcxz', 'poiuytr', 'lkjhgff', 'mnbvc', 'hgfds', 'ytre', 'bvcx',
                  'gfds', 'hgfds', 'uytre', 'gfds', 'ytrewq', 'uytrew', 'iuytre', 'jhgfds', 'nbvcx', 'kjhgfd',
                  'oiuytre', 'hgfdsa', 'nbvcxz', 'jhgfds', 'iuytr', 'jhgfds', 'bvcx', 'hgfdsa', 'uytrew', 'gfdsa',
                  'nbvcx', 'mnbvc', 'iuytr', 'kjhgfd', 'oiuytr', 'hgfdsa', 'nbvcx', 'bvcx', 'fdsa', 'trewq', 'hgfdsa',
                  'nbvcxz', 'hgfds', 'uytrew', 'oiuyt', 'jhgfd', 'mnbvcx', 'uytre', 'oiuytre', 'nbvc', 'jhfd', 'kjhgfd',
                  'nbvcx', 'uytre', 'cxz', 'hgfdsa', 'mnbvcx', 'trewq', 'jhgfds', 'bvcxz', 'jhgfd', 'mnbvc', 'poi',
                  'iuyt', 'oiuyt', 'iuytr', 'iuyt', 'uytr', 'ytre', 'trewq', 'trew', 'ytrew', 'trewq', 'rewq', 'lkjh',
                  'jhg', 'jhgfd', 'hgfds', 'hgfdsa', 'fdsa', 'gfds', 'kjhgfd', 'lkjhg', 'mnbvc', 'nbvcx', 'bvcx', 'vcx',
                  'cxz', 'mnbvcx', 'bvcxz', 'lkjhgf', 'jhgfds', 'gfdsa', 'uytrew', 'trewq', 'oiuyt', 'poiu', 'oiuy',
                  'iuyt', 'uytre', 'ytre', 'trew', 'rewq', 'poiuyt', 'oiuytre', 'iuytrew', 'uytrew', 'trewq', 'lkjhgf',
                  'kjhgf', 'jhgfd', 'hgfds', 'gfds', 'fdsa', 'mnbvc', 'nbvc', 'bvcxz', 'vcxz', 'mnbvcxz', 'kjhgfd',
                  'gfdsa', 'iuytre', 'nbvcxv', 'poiu', 'poiuy', 'poiuyt', 'poiuytr', 'poiuytre', 'poiuytrew', 'oiuyt',
                  'oiuytr', 'oiuytre', 'oiuytrew', 'oiuytrewq', 'iuytr', 'uytre', 'iuytrew', 'iuytrewq', 'uytrew',
                  'ytrew', 'ytrewq', 'ytre', 'trew', 'trewq', 'lkjh', 'kjhg', 'jhgf', 'hgfd', 'gfds', 'fdsa', 'lkjhg',
                  'kjhgfd', 'jhgfds', 'hgfds', 'hgfdsa', 'gfdsa', 'mnbv', 'nbvc', 'bvcx', 'vcxz', 'mnbvc', 'nbvcx',
                  'bvcxz', 'mnbvcx', 'nbvcxz', 'mnbvcxz'
                  ]
    for item in negtive_input:
        convert_keycode(item)


main()
