keycode = {
    'a': 65,
    'b': 66,
    'c': 67,
    'd': 68,
    'e': 69,
    'f': 70,
    'g': 71,
    'h': 72,
    'i': 73,
    'j': 74,
    'k': 75,
    'l': 76,
    'm': 77,
    'n': 78,
    'o': 79,
    'p': 80,
    'q': 81,
    'r': 82,
    's': 83,
    't': 84,
    'u': 85,
    'v': 86,
    'w': 87,
    'x': 88,
    'y': 89,
    'z': 90,
    '0': 48,
    '1': 49,
    '2': 50,
    '3': 51,
    '4': 52,
    '5': 53,
    '6': 54,
    '7': 55,
    '8': 56,
    '9': 57
}


def convert_keycode(input):
    result = ''
    for item in input:
        result += str(keycode[item]) + ','
    result = result[:-1]
    result += ' 1'
    print(result)


def main():
    positive_input = [
        'fjdkls',
        'fjdkls',
        'fjdksl',
        'jfkdls',
        'ghfjdk',
        'hfjdks',
        'fhdjks',
        'fhdjskl',
        'fhdjks',
        'fhdjksl',
        'fgdhjsk',
        'ghfjdksl',
        'fgdhsjka',
        'fgdhjsk',
        'vbcnxmz',
        'vbcnxmz',
        'vbcnxzm',
        'cbnxmz',
        'vbcnxmz',
        'vbcnxmz',
        'vbcxnzm',
        'vcbxnzm',
        'vbcnxmz',
        'tryeuiw',
        'tryeuwi',
        'tryeuwiqo',
        'yreuiwo',
        'tyrueiow',
        'ryeuwio',
        'ryueiwo',
        'yreuiwoq',
        'tyreuiwo',
        'ryeuiwo',
        'yrueiwoq',
        'tyruei',
        'vcbxnm',
        'fgdhsjka',
        'tryeuwi',
        'fjdks',
        'fgdhjlska',
        'gfhdjks',
        'gdhsjakl',
        'vcbnxmz',
        'fgdhjskal',
        'vcbxnmz',
        'tryeuwioq',
        'rteywuiqo',
        'yrueiwop',
        'treywuiq',
        'ytruieowpq',
        'vcbxnzm',
        'dgshjak',
        'rteywuio',
        'dghsjakl',
        'tryeuwioqp',
        'gdhsjka',
        'fgdhjs',
        'vcbxn',
        'fdgshj',
        'fgdhsjk',
        'gfdhjsk',
        'gshajkl',
        'fdgshajk',
        'gfhdjskl',
        'rtyeuwio',
        'gfdhsjkl',
        'vcbxnm',
        'tyrueiow',
        'tyrueiwo',
        'fghj',
        'tewyui',
        'tyreuiow',
        'ryeuwio',
        'etwyquio',
        'yreuiwop',
        'fgdhsjkl',
        'bcxz',
        'fgdhsjakl',
        'ryeuio',
        'yreuiwo',
        'yrueiow',
        'yrueiwo',
        'tryeuwio',
        'fgdhsjk',
        'vcbnxmz',
        'fgdhsjk',
        'tryeuiwo',
        'fgdhsjk',
        'cvbxnm',
        'fgdhsjk',
        'rteywuio',
        'tyurioep',
        'dfsghaj',
        'cvxbnzm',
        'rtyeuiw',
        'vcxbnzm',
        'gdhsjak',
        'ryueiow',
        'tryeuiw',
        'tyreuiw',
        'ytuiroep',
        'etwyuqio',
        'yuitropew',
        'rwtyuqio',
        'yutiroep',
        'treyuwiqo',
        'yrueiwopw',
        'ytuirope',
        'rueiowp',
        'uwiopq',
        'ryueiwo',
        'ureiowp',
        'ywuqio',
        'gfhdjksl',
        'fsghaj',
        'ghfjdksl',
        'dgshjak',
        'hfdjksl',
        'hfdjksl',
        'jdskla',
        'fhdjksla',
        'gfhdjk',
        'gfdhjska',
        'fhdjksl',
        'vbcnmx',
        'cbxnzm',
        'cbnxmx',
        'vcbxnm',
        'bznm',
        'bcnxm',
        'cbxnzm',
        'bcnxm',
        'bcnxzm',
        'cbxnm',
        'vbcnxmz',
        'vcbxnz',
        'vbcnxmz',
        'bxnzm',
        'vcxbnzm',
        'cbxnzm',
        'vbcnxm',
        'yreuiw',
        'trueiow',
        'utiroep',
        'hfdjksl',
        'yeuwiqop',
        'uewioq',
        'dhsjk',
        'hfdjksls',
        'ureiowp',
        'dhsjk',
        'ryueiwo',
        'dhsjak',
        'yrueiow',
        'fdhjsk',
        'cbxnm',
        'cvbxnm',
        'ryeui',
        'gdhsj',
        'tyruieo',
        'cbnxm',
        'utrieo',
        'fgdhsj',
        'rteyuwi',
        'utrieo',
        'cxhjz',
        'fdhjsk',
        'tyurieow',
        'gdhsjak',
        'ryeuwio',
        'hfjdk',
        'uyitorp'
    ]
    negtive_input = [
        'uhv',
        'rghn',
        'xfyu',
        'erthn',
        'cvghui',
        'rth',
        'ergh',
        'dfyui',
        'sdfj',
        'njio',
        'sxc',
        'vghui',
        'ertghn',
        'drtyui',
        'rtyj',
        'wertyj',
        'cgui',
        'xfyuio',
        'rthjm',
        'xdfyuio',
        'rthjm',
        'cghuio',
        'wedfb',
        'xfghu',
        'ijm',
        'oih',
        'efefgh',
        'serfghj',
        'cfyuk',
        'ertyhbn',
        'xdthj',
        'tyuhgcx',
        'wsdfghj',
        'iuytrdc',
        'fgui',
        'sfdgfh',
        'hfsd',
        'sbhjiu',
        'weuh',
        'bchui',
        'xcfgyu',
        'rth',
        'werty',
        'oiug',
        'drtyh',
        'xcvbhu',
        'poiuyg',
        'qwscv',
        'cyui',
        'oiuytf',
        'ertyhn',
        'qscvb',
        'cfyu',
        'oiuyt',
        'kjhv',
        'srtyu',
        'zxcgyu',
        'iuytrd',
        'zsrtyj',
        'cgh',
        'iuyg',
        'erth',
        'sertyui',
        'cfgyuio',
        'oiuytd',
        'wdfghj',
        'xcghui',
        'dtyui',
        'rdftgh',
        'gvhu',
        'txrfuygk',
        'ijiuh',
        'vghj',
        'xcfg',
        'iuyf',
        'edfghjk',
        'xfyui',
        'nhre',
        'asdfgui',
        'cgui',
        'dfghn',
        'dfghj',
        'yuio',
        'oihg',
        'rghn',
        'xfyui',
        'uygfc',
        'efgh',
        'hgfrfghn',
        'cfghu',
        'uigyuf',
        'ezrtxgfk',
        'hgdv',
        'ashck',
        'qvebick',
        'qxgk',
        'sdabhvioz',
        'weiurdacsb',
        'zuvcdgks',
        'sdjivhs',
        'wqfbucow',
        'bdhuca',
        'bsaf',
        'efbiwuo',
        'sdauhicg',
        'wudviy',
        'vbieuo',
        'bfhjwa',
        'sbjkadv',
        'qbufw',
        'abiu',
        'bxiueo',
        'abvio',
        'absvidghs',
        'bjscgiu',
        'hfiea',
        'sdiaco',
        'biufa',
        'baivsoa',
        'bcuaui',
        'bwisvbid',
        'vdsbaico',
        'bahcoei',
    ]
    for item in positive_input:
        convert_keycode(item)


main()
