# Generated by Django 2.1 on 2018-09-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.IntegerField(default=0)),
                ('sidebar', models.IntegerField(default=0)),
                ('footer', models.IntegerField(default=0)),
                ('section_num', models.IntegerField(default=0)),
            ],
        ),
    ]
