# Generated by Django 2.1 on 2018-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default='', max_length=64)),
                ('section_id', models.IntegerField(default=0)),
                ('pos', models.IntegerField(default=0)),
                ('stack_num', models.IntegerField(default=0)),
                ('padding', models.CharField(default='', max_length=64)),
                ('margin', models.CharField(default='', max_length=64)),
                ('text_content', models.TextField(null=True)),
                ('font_size', models.CharField(default='16px', max_length=64)),
                ('font_color', models.CharField(default='black', max_length=64)),
                ('background_color', models.CharField(default='white', max_length=64)),
                ('pic_content', models.ImageField(null=True, upload_to='img')),
                ('name', models.CharField(default='anonymous', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(default=0)),
                ('style', models.CharField(default='', max_length=64)),
                ('name', models.CharField(default='', max_length=64)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
