# Generated by Django 2.1 on 2018-09-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planb', '0002_block_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='pos',
            new_name='column',
        ),
        migrations.RemoveField(
            model_name='block',
            name='stack_num',
        ),
    ]
