# Generated by Django 2.1 on 2018-10-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planb', '0003_auto_20180930_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='margin',
        ),
        migrations.AlterField(
            model_name='block',
            name='padding',
            field=models.CharField(default='0 0 0 0', max_length=64),
        ),
    ]
