# Generated by Django 2.1 on 2018-08-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='font_size',
            field=models.CharField(default='16px', max_length=64),
        ),
    ]
