# Generated by Django 2.1 on 2018-08-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plana', '0003_block_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='status',
        ),
        migrations.AddField(
            model_name='block',
            name='height_css',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='block',
            name='width_css',
            field=models.CharField(default='', max_length=100),
        ),
    ]
