# Generated by Django 2.1 on 2018-08-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plana', '0004_auto_20180827_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
