# Generated by Django 2.1 on 2018-08-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plana', '0005_block_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='height_css',
        ),
        migrations.RemoveField(
            model_name='block',
            name='width_css',
        ),
    ]
