# Generated by Django 2.1 on 2018-09-02 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plana', '0006_auto_20180827_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Horizonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.IntegerField(default=0)),
                ('sidebar', models.IntegerField(default=0)),
                ('footer', models.IntegerField(default=0)),
                ('section_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TextPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('font_size', models.CharField(default='16px', max_length=64)),
                ('font_color', models.CharField(default='black', max_length=64)),
                ('background_image', models.ImageField(upload_to='img')),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='block',
            old_name='type',
            new_name='content_type',
        ),
        migrations.RemoveField(
            model_name='block',
            name='color',
        ),
        migrations.AddField(
            model_name='block',
            name='container_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='container_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text',
            name='background_color',
            field=models.CharField(default='white', max_length=64),
        ),
        migrations.AlterField(
            model_name='text',
            name='font_color',
            field=models.CharField(default='black', max_length=64),
        ),
        migrations.AddField(
            model_name='textpic',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plana.Block'),
        ),
    ]
