# Generated by Django 2.1 on 2018-09-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plana', '0007_auto_20180902_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grid',
        ),
        migrations.DeleteModel(
            name='Horizonal',
        ),
        migrations.DeleteModel(
            name='Vertical',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='container_id',
            new_name='section_id',
        ),
        migrations.RemoveField(
            model_name='block',
            name='container_type',
        ),
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
        migrations.AddField(
            model_name='section',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
