# Generated by Django 2.1 on 2018-09-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plana', '0009_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='block',
        ),
        migrations.RemoveField(
            model_name='text',
            name='block',
        ),
        migrations.RemoveField(
            model_name='textpic',
            name='block',
        ),
        migrations.AddField(
            model_name='block',
            name='background_color',
            field=models.CharField(default='white', max_length=64),
        ),
        migrations.AddField(
            model_name='block',
            name='font_color',
            field=models.CharField(default='black', max_length=64),
        ),
        migrations.AddField(
            model_name='block',
            name='font_size',
            field=models.CharField(default='16px', max_length=64),
        ),
        migrations.AddField(
            model_name='block',
            name='name',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='block',
            name='pic_content',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='block',
            name='pic_text_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='text_content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Pic',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='TextPic',
        ),
    ]
